# Generated by Django 4.2.10 on 2024-02-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ingrese el nombre o razón social", max_length=200
                    ),
                ),
                (
                    "tipo_de_persona",
                    models.CharField(
                        choices=[("N", "Persona Natural"), ("J", "Persona Jurídica")],
                        max_length=1,
                    ),
                ),
                (
                    "clasificacion",
                    models.CharField(
                        choices=[
                            ("P", "Pequeño"),
                            ("M", "Mediano"),
                            ("G", "Gran Contribuyente"),
                        ],
                        max_length=1,
                        verbose_name="clasificación",
                    ),
                ),
                (
                    "nrc",
                    models.CharField(
                        help_text="Número de registro del contribuyente",
                        max_length=12,
                        verbose_name="NRC",
                    ),
                ),
                (
                    "nit",
                    models.CharField(
                        help_text="Número de Identificación tributaria",
                        max_length=20,
                        verbose_name="NIT",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Dirección"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "cliente",
                    models.BooleanField(default=False, verbose_name="¿Cliente?"),
                ),
                (
                    "proveedor",
                    models.BooleanField(default=False, verbose_name="¿Proveedor?"),
                ),
            ],
        ),
    ]
