# Generated by Django 5.0.2 on 2024-02-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumidorFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_de_documento', models.CharField(choices=[('D', 'DUI'), ('N', 'NIT'), ('O', 'Otro')], max_length=1)),
                ('numero_de_documento', models.CharField(max_length=10, verbose_name='número de documento')),
            ],
        ),
    ]
