# Generated by Django 5.0.2 on 2024-02-24 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0002_consumidorfinal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumidorfinal',
            options={'verbose_name': 'consumidor final', 'verbose_name_plural': 'consumidores finales'},
        ),
    ]
