# Generated by Django 4.2.10 on 2024-02-22 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("empresas", "0001_initial"),
        ("contactos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VentasAContribuyente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_de_sucursal", models.CharField(max_length=100)),
                (
                    "tipo_de_comprobate",
                    models.CharField(
                        choices=[
                            ("CCF", "Comprobante de Crédito Fiscal"),
                            ("NDC", "Nota de Crédito"),
                        ],
                        max_length=3,
                    ),
                ),
                ("nombre_de_comprobantes", models.CharField(max_length=100)),
                ("numero_de_resolucion", models.CharField(max_length=30)),
                ("serie_de_documento", models.CharField(max_length=30)),
                ("nombre_del_cliente", models.CharField(max_length=200)),
                (
                    "numero_de_documento",
                    models.CharField(
                        max_length=35, verbose_name="número de comprobante"
                    ),
                ),
                ("venta_neta", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "iva",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="IVA"
                    ),
                ),
                (
                    "retencion_de_iva",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("sub_total", models.DecimalField(decimal_places=2, max_digits=8)),
                ("venta_excenta", models.DecimalField(decimal_places=2, max_digits=8)),
                ("total", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="empresas.empresa",
                    ),
                ),
                (
                    "nrc_cliente",
                    models.ForeignKey(
                        limit_choices_to={"cliente": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contactos.contacto",
                    ),
                ),
                (
                    "numero_sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="empresas.sucursal",
                        verbose_name="número de sucursal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VentasAConsumidorFinal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_de_sucursal", models.CharField(max_length=100)),
                (
                    "tipo_de_comprobate",
                    models.CharField(
                        choices=[
                            ("FAC", "Factura de Consumidor Final"),
                            ("NDC", "Nota de Crédito"),
                        ],
                        max_length=3,
                    ),
                ),
                ("nombre_de_comprobantes", models.CharField(max_length=100)),
                ("numero_de_resolucion", models.CharField(max_length=30)),
                ("serie_de_documento", models.CharField(max_length=30)),
                ("nombre_del_cliente", models.CharField(max_length=200)),
                (
                    "numero_de_documento",
                    models.CharField(max_length=35, verbose_name="número de documento"),
                ),
                (
                    "tipo_de_venta",
                    models.CharField(
                        choices=[("IN", "Interna"), ("EX", "Exportación")], max_length=2
                    ),
                ),
                (
                    "total_venta_gravada",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("venta_neta", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "iva",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="IVA"
                    ),
                ),
                ("sub_total", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "retencion_de_iva",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "total_venta_excenta",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("total_general", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "codigo_cliente",
                    models.ForeignKey(
                        limit_choices_to={"cliente": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contactos.contacto",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="empresas.empresa",
                    ),
                ),
                (
                    "numero_sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="empresas.sucursal",
                        verbose_name="número de sucursal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Compras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_de_proveedor", models.CharField(max_length=200)),
                (
                    "tipo_de_comprobante",
                    models.CharField(
                        choices=[
                            ("CCF", "Comprobante de Crédito Fiscal"),
                            ("EXP", "Exportación"),
                            ("PLZ", "Poliza"),
                            ("NDC", "Nota de Crédito"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "numero_de_comprobante",
                    models.CharField(
                        max_length=32, verbose_name="número de comprobante"
                    ),
                ),
                (
                    "numero_de_serie",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("fecha", models.DateField()),
                (
                    "tipo_de_compra",
                    models.CharField(
                        choices=[("INT", "Interna"), ("IMP", "Importación")],
                        max_length=3,
                    ),
                ),
                ("compra_neta", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "iva",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="I.V.A."
                    ),
                ),
                (
                    "percepcion_iva",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="percepción I.V.A."
                    ),
                ),
                ("sub_total", models.DecimalField(decimal_places=2, max_digits=8)),
                ("compra_excenta", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "compra_excluida",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "tipo_de_gasto",
                    models.CharField(
                        choices=[
                            ("CST", "Costo"),
                            ("GAD", "Gasto de Administración"),
                            ("GAV", "Gasto de Venta"),
                            ("GAF", "Gasto Financiero"),
                            ("OGA", "Otro Gasto"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="empresas.empresa",
                    ),
                ),
                (
                    "nrc_proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contactos.contacto",
                    ),
                ),
            ],
        ),
    ]
