# Generated by Django 4.2.10 on 2024-02-23 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0007_sucursal_codigo"),
        ("contabilidad", "0002_alter_compras_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ventasaconsumidorfinal",
            name="numero_sucursal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="empresas.sucursal",
                verbose_name="sucursal",
            ),
        ),
    ]
