# Generated by Django 5.0.2 on 2024-02-24 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_remove_compras_nombre_de_proveedor_and_more'),
        ('contactos', '0002_consumidorfinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='proveedor',
            field=models.ForeignKey(limit_choices_to={'proveedor': True}, on_delete=django.db.models.deletion.PROTECT, to='contactos.contacto'),
        ),
    ]
