# Generated by Django 5.0.2 on 2024-02-24 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_alter_compras_proveedor'),
        ('contactos', '0003_alter_consumidorfinal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventasaconsumidorfinal',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contactos.consumidorfinal'),
            preserve_default=False,
        ),
    ]
