# Generated by Django 5.0.2 on 2024-02-25 15:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_ventasaconsumidorfinal_cliente'),
        ('empresas', '0007_sucursal_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventasacontribuyente',
            name='venta_excenta',
        ),
        migrations.RemoveField(
            model_name='ventasacontribuyente',
            name='venta_neta',
        ),
        migrations.AddField(
            model_name='ventasacontribuyente',
            name='fecha',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='ventasacontribuyente',
            name='ventas_exentas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ventasacontribuyente',
            name='ventas_gravadas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ventasacontribuyente',
            name='ventas_no_sujetas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ventasacontribuyente',
            name='retencion_de_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ventasacontribuyente',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ventasacontribuyente',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.sucursal'),
        ),
        migrations.AlterField(
            model_name='ventasacontribuyente',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
