# Generated by Django 5.0.2 on 2024-02-25 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0009_ventasaconsumidorfinal_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventasaconsumidorfinal',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='ventasaconsumidorfinal',
            name='retencion_de_iva',
        ),
        migrations.RemoveField(
            model_name='ventasaconsumidorfinal',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='ventasaconsumidorfinal',
            name='total_general',
        ),
        migrations.RemoveField(
            model_name='ventasaconsumidorfinal',
            name='total_venta_excenta',
        ),
        migrations.RemoveField(
            model_name='ventasaconsumidorfinal',
            name='total_venta_gravada',
        ),
        migrations.RemoveField(
            model_name='ventasaconsumidorfinal',
            name='venta_neta',
        ),
    ]
