# Generated by Django 4.2.10 on 2024-03-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contabilidad", "0011_ventasaconsumidorfinal_retencion_de_iva_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ventasaconsumidorfinal",
            name="tipo_de_comprobante",
            field=models.CharField(
                choices=[
                    ("FAC", "Factura de Consumidor Final"),
                    ("NDC", "Nota de Crédito"),
                ],
                default="FAC",
                max_length=3,
            ),
        ),
    ]
