# Generated by Django 4.2.10 on 2024-03-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contabilidad", "0013_alter_ventasaconsumidorfinal_tipo_de_comprobante"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ventasaconsumidorfinal",
            name="tipo_de_comprobante",
            field=models.CharField(
                choices=[
                    ("FCF", "Factura de Consumidor Final"),
                    ("NDC", "Nota de Crédito"),
                ],
                default="FCF",
                max_length=3,
            ),
        ),
    ]
