# Generated by Django 4.2.10 on 2024-03-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contabilidad", "0015_alter_ventasaconsumidorfinal_tipo_de_comprobante"),
    ]

    operations = [
        migrations.AddField(
            model_name="ventasacontribuyente",
            name="anulado",
            field=models.BooleanField(default=False),
        ),
    ]
