# Generated by Django 4.2.10 on 2024-03-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contabilidad", "0016_ventasacontribuyente_anulado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compras",
            name="tipo_de_comprobante",
            field=models.CharField(
                choices=[
                    ("CCF", "Comprobante de Crédito Fiscal"),
                    ("EXP", "Exportación"),
                    ("PLZ", "Poliza"),
                    ("NDC", "Nota de Crédito"),
                ],
                default="CCF",
                max_length=3,
            ),
        ),
    ]
