# Generated by Django 4.2.10 on 2024-03-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contabilidad", "0017_alter_compras_tipo_de_comprobante"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compras",
            name="tipo_de_compra",
            field=models.CharField(
                choices=[("INT", "Interna"), ("IMP", "Importación")],
                default="INT",
                max_length=3,
            ),
        ),
    ]
