# Generated by Django 4.2.10 on 2024-03-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contabilidad", "0018_alter_compras_tipo_de_compra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compras",
            name="tipo_de_gasto",
            field=models.CharField(
                choices=[
                    ("CST", "Costo"),
                    ("GAD", "Gasto de Administración"),
                    ("GAV", "Gasto de Venta"),
                    ("GAF", "Gasto Financiero"),
                    ("OGA", "Otro Gasto"),
                ],
                default="CST",
                max_length=3,
            ),
        ),
    ]
