# Generated by Django 4.2.10 on 2024-03-13 21:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contabilidad", "0019_alter_compras_tipo_de_gasto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compras",
            name="compra_excenta",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=8
            ),
        ),
        migrations.AlterField(
            model_name="compras",
            name="compra_excluida",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=8
            ),
        ),
        migrations.AlterField(
            model_name="compras",
            name="compra_neta",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=8
            ),
        ),
        migrations.AlterField(
            model_name="compras",
            name="iva",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="I.V.A.",
            ),
        ),
        migrations.AlterField(
            model_name="compras",
            name="percepcion_iva",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="percepción I.V.A.",
            ),
        ),
        migrations.AlterField(
            model_name="compras",
            name="sub_total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=8
            ),
        ),
        migrations.AlterField(
            model_name="compras",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=8
            ),
        ),
    ]
