# Generated by Django 4.2.10 on 2024-03-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contabilidad", "0021_compras_numero_de_comprobante"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ventasaconsumidorfinal",
            name="numero_de_documento",
        ),
        migrations.AddField(
            model_name="ventasaconsumidorfinal",
            name="numero_de_resolucion",
            field=models.CharField(
                default="", max_length=35, verbose_name="número de resolución"
            ),
            preserve_default=False,
        ),
    ]
