# Generated by Django 4.2.10 on 2024-03-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "contabilidad",
            "0022_remove_ventasaconsumidorfinal_numero_de_documento_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ventasaconsumidorfinal",
            name="numero_de_documento",
            field=models.CharField(
                default="", max_length=35, verbose_name="número de documento"
            ),
            preserve_default=False,
        ),
    ]
