# Generated by Django 4.2.10 on 2024-03-13 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contactos", "0003_alter_consumidorfinal_options"),
        ("contabilidad", "0023_ventasaconsumidorfinal_numero_de_documento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ventasaconsumidorfinal",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="contactos.consumidorfinal",
            ),
        ),
    ]
