# Generated by Django 4.2.10 on 2024-03-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contabilidad", "0024_alter_ventasaconsumidorfinal_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="ventasacontribuyente",
            name="numero_de_resolucion",
            field=models.CharField(
                default="", max_length=20, verbose_name="número de resolución"
            ),
            preserve_default=False,
        ),
    ]
