# Generated by Django 4.2.10 on 2024-03-13 22:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contabilidad", "0025_ventasacontribuyente_numero_de_resolucion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ventasacontribuyente",
            name="iva",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="IVA",
            ),
        ),
    ]
