# Generated by Django 4.2.13 on 2024-06-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contabilidad", "0026_alter_ventasacontribuyente_iva"),
    ]

    operations = [
        migrations.AddField(
            model_name="ventasacontribuyente",
            name="clase_de_documento",
            field=models.CharField(
                choices=[
                    ("IMP", "impreso"),
                    ("FOU", "formulario único"),
                    ("DTE", "documento tributario electrónico"),
                ],
                default="IMP",
                max_length=3,
            ),
        ),
    ]
