# Generated by Django 4.2.13 on 2024-06-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contabilidad", "0027_ventasacontribuyente_clase_de_documento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ventasacontribuyente",
            name="numero_de_resolucion",
            field=models.CharField(max_length=100, verbose_name="número de resolución"),
        ),
    ]
