# Generated by Django 4.2.10 on 2024-02-23 21:04

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0002_alter_empresa_options_alter_sucursal_options_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grupo",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": " Usuario", "verbose_name_plural": " Usuarios"},
        ),
        migrations.AlterField(
            model_name="user",
            name="empresas",
            field=models.ManyToManyField(blank=True, to="empresas.empresa"),
        ),
    ]
