# Generated by Django 4.2.10 on 2024-02-23 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="empresa",
            options={"verbose_name": " Empresa", "verbose_name_plural": " Empresas"},
        ),
        migrations.AlterModelOptions(
            name="sucursal",
            options={"verbose_name": " Sucursal", "verbose_name_plural": " Sucursales"},
        ),
        migrations.CreateModel(
            name="Comprobante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_de_comprobante",
                    models.CharField(
                        choices=[
                            ("FCF", "Factura de consumidor final"),
                            ("CCF", "Comprobante de crédito fiscal"),
                            ("NDC", "Nota de crédito"),
                            ("PLZ", "Poliza"),
                            ("FEX", "Factura de exportación"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "numero_de_resolucion",
                    models.CharField(
                        max_length=20, verbose_name="número de resolición"
                    ),
                ),
                ("serie_de_documento", models.CharField(max_length=20)),
                ("marcar_como_actual", models.BooleanField(default=False)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="empresas.empresa",
                    ),
                ),
            ],
        ),
    ]
