# Generated by Django 4.2.10 on 2024-02-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0002_alter_empresa_options_alter_sucursal_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="nit",
            field=models.CharField(
                default="",
                help_text="Número de identificación tributario",
                max_length=10,
                unique=True,
                verbose_name="NIT",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="empresa",
            name="nrc",
            field=models.CharField(
                default="",
                help_text="Número de regisctro de contribuyente",
                max_length=10,
                unique=True,
                verbose_name="NRC",
            ),
            preserve_default=False,
        ),
    ]
