# Generated by Django 4.2.10 on 2024-02-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0003_empresa_nit_empresa_nrc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="nit",
            field=models.CharField(
                help_text="Número de identificación tributario",
                max_length=20,
                unique=True,
                verbose_name="NIT",
            ),
        ),
    ]
