# Generated by Django 4.2.10 on 2024-02-23 21:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0004_alter_empresa_nit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sucursal",
            name="tiraje",
        ),
    ]
