# Generated by Django 4.2.10 on 2024-02-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0005_remove_sucursal_tiraje"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comprobante",
            name="numero_de_resolucion",
            field=models.CharField(max_length=20, verbose_name="número de resolución"),
        ),
    ]
