# Generated by Django 4.2.10 on 2024-02-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0006_alter_comprobante_numero_de_resolucion"),
    ]

    operations = [
        migrations.AddField(
            model_name="sucursal",
            name="codigo",
            field=models.CharField(default="", max_length=10, verbose_name="código"),
            preserve_default=False,
        ),
    ]
