# Generated by Django 4.2.10 on 2024-03-12 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0007_sucursal_codigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="comprobante",
            name="sucursal",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="empresas.sucursal",
            ),
            preserve_default=False,
        ),
    ]
